safe: false

# build settings
markdown: kramdown
highlighter: rouge
lsi: false
permalink: /:title

title: "Corporations base"
description: "Online base of corporations"
baseurl: ""
url: "https://lex45.github.io/" # replace by your site's url
twitter_username: your-name
github_username:  lukas-h # (your name)
accent: "#f7f7e6" # accent color for blog column

author: "Jason"
address: "New irland"
email: "cccorp@copl.com"

# google analytics tracking code, please change the value
g_analytics: ""

# language settings
isolang: en

# exclude files
exclude:
  - LICENSE
  - README.md
