title: Corporations database
author: Jason
email: jason54@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  database of corporations

twitter_username: macrod68
github_username:  macrod68

sass:
    style: compressed
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap